"""ajout table retraits

Revision ID: 8ba877de1279
Revises: 
Create Date: 2026-03-14 21:15:55.106985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba877de1279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('reseau', sa.String(length=30), nullable=False),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('reference_transaction', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('note_admin', sa.Text(), nullable=True),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('valide_le', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('retraits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('reseau', sa.String(length=30), nullable=False),
    sa.Column('numero_telephone', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('reference_admin', sa.String(length=100), nullable=True),
    sa.Column('note_admin', sa.Text(), nullable=True),
    sa.Column('traite_le', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('soldes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('penalites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tontine_id', sa.Integer(), nullable=False),
    sa.Column('montant_du', sa.Float(), nullable=False),
    sa.Column('montant_penalite', sa.Float(), nullable=False),
    sa.Column('taux', sa.Float(), nullable=True),
    sa.Column('mois_reference', sa.String(length=7), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('mois_impaye', sa.Integer(), nullable=True),
    sa.Column('note_admin', sa.Text(), nullable=True),
    sa.Column('regularise_le', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tontine_id', sa.Integer(), nullable=True),
    sa.Column('type_transaction', sa.String(length=30), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('sens', sa.String(length=10), nullable=False),
    sa.Column('solde_avant', sa.Float(), nullable=True),
    sa.Column('solde_apres', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.drop_column('contenu_html')

    op.drop_table('transactions')
    op.drop_table('penalites')
    op.drop_table('soldes')
    op.drop_table('retraits')
    op.drop_table('recharges')
    # ### end Alembic commands ###
